version: '3.8'

services:
  postgres:
    image: postgres:13.3
    container_name: postgres-broker
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
        - ./data:/var/lib/postgresql/data