name: Makefile CI

on:
  workflow_dispatch:
  push:
    branches: 
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21.5'
      
      - name: Where Are We
        run: ls -l

      - name: Install dependencies
        run: make resolve

      - name: Run tests
        run: make test
