name: Deploy Image to GHCR

env:
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Setup Go'
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21.5'

      - name: 'Build Binary'
        run: make build

  push-store-image:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GH_TOKEN}}

      - name: 'Build Inventory Image'
        run: |
          docker build . --tag ghcr.io/sad-project-fall-2023/broker:${{github.sha}}
          docker push ghcr.io/sad-project-fall-2023/broker:${{github.sha}}